export const CHANGE_EVENTS_TAB = "CHANGE_EVENTS_TAB";
export const CHANGE_FEDERAL_STATE_RADIO = "CHANGE_FEDERAL_STATE_RADIO";
export const GET_URL_HASH = "GET_URL_HASH";
export const GET_URL_HASH_SUCCESS = "GET_URL_HASH_SUCCESS";
export const SELECTION_REQUEST_FAILED = "SELECTION_REQUEST_FAILED";
export const CHANGE_FEDERAL_STATE_RADIO_OLD_EVENT = "CHANGE_FEDERAL_STATE_RADIO_OLD_EVENT";