export const LIVE_EVENTS_TAB = 'live';
export const PENDING_EVENTS_TAB = 'pending';
export const ARCHIVED_EVENTS_TAB = 'archive';
export const FEDERAL_RADIO_BUTTON = 'federal';
export const STATES_LEGS = ['CO', 'AZ', 'NC', 'OR', 'VA']
export const FEDERAL_STATE_RADIO_BUTTONS = [FEDERAL_RADIO_BUTTON, ...STATES_LEGS];
export const EVENT_MENU_ITEM = 'events';
export const MOC_MENU_ITEM = 'mocs';
export const RESEARCHER_MENU_ITEM = 'researcher';
export const RESOURCES_MENU_ITEM = 'resources'
export const eventTabOptions = [LIVE_EVENTS_TAB, PENDING_EVENTS_TAB, ARCHIVED_EVENTS_TAB];
export const navMenuItems = [EVENT_MENU_ITEM, MOC_MENU_ITEM, RESEARCHER_MENU_ITEM, RESOURCES_MENU_ITEM];