export const REQUEST_ALL_RSVPS = "REQUEST_ALL_RSVPS";
export const REQUEST_ALL_RSVPS_SUCCESS = "REQUEST_ALL_RSVPS_SUCCESS";
export const RSVP_REQUEST_FAILED = "RSVP_REQUEST_FAILED";
export const REQUEST_ALL_EVENTS_WITH_RSVPS = "REQUEST_ALL_EVENTS_WITH_RSVPS";
export const REQUEST_ALL_EVENTS_WITH_RSVPS_SUCCESS = "REQUEST_ALL_EVENTS_WITH_RSVPS_SUCCESS";