import { makeConstant } from "../../utils";
const STATE_BRANCH = 'RESEARCHERS';

export const REQUEST_FAILED = makeConstant(STATE_BRANCH, 'REQUEST_FAILED');

export const REQUEST_ALL_RESEARCHERS = makeConstant(STATE_BRANCH, 'REQUEST_ALL_RESEARCHERS');
export const SET_ALL_RESEARCHERS = makeConstant(STATE_BRANCH, 'SET_ALL_RESEARCHERS');

export const REQUEST_RESEARCHER_BY_ID = makeConstant(STATE_BRANCH, 'REQUEST_RESEARCHER_BY_ID');
export const REQUEST_RESEARCHER_BY_ID_FAILED = makeConstant(STATE_BRANCH, 'REQUEST_RESEARCHER_BY_ID_FAILED');

export const UPDATE_RESEARCHER_MOCS = makeConstant(STATE_BRANCH, 'UPDATE_RESEARCHER_MOCS');
export const REMOVE_ASSIGNMENT = makeConstant(STATE_BRANCH, 'REMOVE_ASSIGNMENT');
export const REMOVE_ASSIGNMENT_SUCCESS = makeConstant(STATE_BRANCH, 'REMOVE_ASSIGNMENT_SUCCESS');
export const ASSIGN_MOC_TO_RESEARCHER = makeConstant(STATE_BRANCH, 'ASSIGN_MOC_TO_RESEARCHER');
export const ASSIGN_MOC_TO_RESEARCHER_SUCCESS = makeConstant(STATE_BRANCH, 'ASSIGN_MOC_TO_RESEARCHER_SUCCESS');
export const ADD_AND_ASSIGN_TO_RESEARCHER = makeConstant(STATE_BRANCH, 'ADD_AND_ASSIGN_TO_RESEARCHER');
export const ADD_AND_ASSIGN_TO_RESEARCHER_SUCCESS = makeConstant(STATE_BRANCH, 'ADD_AND_ASSIGN_TO_RESEARCHER_SUCCESS');

export const SET_RESEARCHER_EMAIL_DATA = makeConstant(STATE_BRANCH, 'SET_RESEARCHER_EMAIL_DATA');