import { makeConstant } from "../../utils";

const STATE_BRANCH = "SUBSCRIBERS";

export const REQUEST_FAILED = makeConstant(STATE_BRANCH, 'REQUEST_FAILED');
export const SUBMIT_SUBSCRIBER = makeConstant(STATE_BRANCH, 'SUBMIT_SUBSCRIBER');
export const SUBMIT_SUBSCRIBER_SUCCESS = makeConstant(STATE_BRANCH, 'SUBMIT_SUBSCRIBER_SUCCESS');
export const REQUEST_ALL_SUBSCRIBERS = makeConstant(STATE_BRANCH, 'REQUEST_ALL_SUBSCRIBERS');
export const REQUEST_ALL_SUBSCRIBERS_SUCCESS = makeConstant(STATE_BRANCH, 'REQUEST_ALL_SUBSCRIBERS_SUCCESS');
export const UPDATE_EMAIL_DATA = makeConstant(STATE_BRANCH, 'UPDATE_EMAIL_DATA');