import { makeConstant } from "../../utils";

const STATE_BRANCH = "SUBSCRIBERS";

export const REQUEST_FAILED = makeConstant(STATE_BRANCH, 'REQUEST_FAILED');
export const SUBMIT_SUBSCRIBER = makeConstant(STATE_BRANCH, 'SUBMIT_SUBSCRIBER');
export const SUBMIT_SUBSCRIBER_SUCCESS = makeConstant(STATE_BRANCH, 'SUBMIT_SUBSCRIBER_SUCCESS');
export const REQUEST_ALL_SUBSCRIBERS = makeConstant(STATE_BRANCH, 'REQUEST_ALL_SUBSCRIBERS');
export const REQUEST_ALL_SUBSCRIBERS_SUCCESS = makeConstant(STATE_BRANCH, 'REQUEST_ALL_SUBSCRIBERS_SUCCESS');
export const REQUEST_SUBSCRIBER_BY_EMAIL = makeConstant(STATE_BRANCH, 'REQUEST_SUBSCRIBER_BY_EMAIL');
export const REQUEST_SUBSCRIBER_BY_EMAIL_SUCCESS = makeConstant(STATE_BRANCH, 'REQUEST_SUBSCRIBER_BY_EMAIL_SUCCESS');
