export const GET_USERS = "GET_USERS";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAILED = "GET_USERS_FAILED";
export const REQUEST_USER_BY_ID = "REQUEST_USER_BY_ID";
export const RECEIVE_USER = "RECEIVE_USER";
export const REQUEST_USER_BY_ID_FAILED = "REQUEST_USER_BY_ID_FAILED";
export const REQUEST_RESEARCHER = "REQUEST_RESEARCHER";
export const UPDATE_USER_MOCS = "UPDATE_USER_MOCS";